site_name: "FastAPI Views"
site_description: "FastAPI Class Views and other utils"
theme:
  name: "material"
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
repo_name: performance-media/fastapi-views
repo_url: https://github.com/performancemedia/fastapi-views
nav:
  - "FastAPI Views": index.md
  - "Installation": installation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            docstring_style: sphinx
